### ISSUE TITLE
Displaying info on a scoreboard. 

### ISSUE THREAD

**Issue by snaildos** [TimelessMC/Afterlife#1]
Dude, this is awesome! I live your work. It's different and awesome. Now, I'd honestly want to use this plugin, except, that there's not a scoreboard display. Please add that so I can open a kitpvp on my server!
Your proberly confused on what I want added, but what I want is:

- Floating text board
- info on a scoreboard which can be edited in config.

But other then that, I'd be using your plugin, please add those so I can use it :D

**Comment by Atm85** [comment]
Congratulations! These have been planned features for a while and will be in a future update!
